if you want to help me out or support the compilation in some way this would help!

Bitcoin - 3NCeoDCHSLTC1qSNKWs4AR9GTF6Jz8Sp2A
Bitcoin cash - qp5ghvashz2ejzusdrzpg4n6smdcykxysgh6j3eplq
Chain link - 0x0Bb1C31C41bfAa4102215EDFB6dCeF87600E0eB3
Ethereum - 0x2C7e1962b13d3Ec9Bd78BF761E9Cb9f7Bb0c0784
