language: node_js
node_js: string
env:
  - CXX=g++-4.8
steps:
  - name: install astyle
    run: sudo apt-get install -y astyle
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
