excluded_words:
  - cdda
  - dda
  - cata
  - Zets
  - overmap
  - Magiclysm
  - uncraft
  - Nocts
  - tefnut
  - evac
  - cyberjunkie
  - medikit
  - triffgus
  - wildy
  - D'ya
  - bfg
  - omnicam
  - attunements
  - technomancer
  - factionless
  - npc
  - npcs
  - tshirt
  - bommers
  - veh
  - Dinomod
  - Nechronica
  - IchBinNexus
  - PoraComp
  - Pharm
  - Porawep
  - Touhou
  - jrr
  - eyebot
  - orjson
  - shutil
  - reformatter
  - bads
  - FictonalWeapons
  - fic
  - ficmags
  - necronimicron
  - cbm
  - cbms
  - boxs
  - Weetabix
  - Oatibix
  - Nesquik
  - Jordans
  - Rais
  - Krave
  - Choco
  - Wkk
  - Alpen
  - Mcvitie
  - Frosties
  - Frusli
  - Lizis
  - Oomf
  - Chia
  - Moma
  - Superseeded
  - vitA
  - vitC
  - kelloggs
  - oatie
  - jihelucake
  - toastem
  - spezi
  - colamdew
  - fchicken
  - nachosc
  - nachosm
  - nachosmc
  - toasterpastryfrozen
  - sloppyjoe
  - grahmcrackers
  - lutefisk
  - kompot
  - chilidogs
  - crispycran
  - dayquil
  - ecig
  - foon
  - halligan
  - mbag
  - slingpack
  - neccowafers
  - picklocks
  - quikclot
  - tazer
  - teleumbrella
  - vacutainer
  - veggy
  - xacto
  - xanax
  - ssWWWWWWWWssssssssssssss
  - tttt
  - ttttt
  - rrr
  - brandcerealmod
  - KantoJolto
