name: First interaction

on: push

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the git and thanks for your first interaction.'
        pr-message: 'Welcome to the git and thanks for your first contribution.'
