name: JSON style check

on:
  push:
    branches:
    - Experimental-Mod-Pack
    paths:
    - '**.json'

jobs:
  style-json:
    name: JSON style check

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: JSON style check
        run: make style-json
      - name: Display Corrections
        if: failure()
        run: git diff
