name: TOC Generator

on:
  push:
    branches:
    - Experimental-Mod-Pack
    paths:
    - '**.md'

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: self-hosted
    steps:
      - uses: technote-space/toc-generator@v3
